#ifndef PROCESS_LIMITS
#define Q1_MIN_ADD_TIME 1
#define Q1_MAX_ADD_TIME 5
#define Q1_AV_ADD_TIME ((Q1_MAX_ADD_TIME + Q1_MIN_ADD_TIME) / 2.0)

#define Q1_MIN_PROC_TIME 0
#define Q1_MAX_PROC_TIME 4
#define Q1_AV_PROC_TIME ((Q1_MAX_PROC_TIME + Q1_MIN_PROC_TIME) / 2.0)

#define Q2_MIN_ADD_TIME 0
#define Q2_MAX_ADD_TIME 3
#define Q2_AV_ADD_TIME ((Q2_MAX_ADD_TIME + Q2_MIN_ADD_TIME) / 2.0)

#define Q2_MIN_PROC_TIME 0
#define Q2_MAX_PROC_TIME 1
#define Q2_AV_PROC_TIME ((Q2_MAX_PROC_TIME + Q2_MIN_PROC_TIME) / 2.0)


#endif // !PROCESS_LIMITS
